[package]
name = "chip8_emu"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.28.0"
rand = "0.9.0"
emu-abstractions = { git = "https://github.com/Scott8440/emu-abstractions.git" }

[dev-dependencies]
pretty_assertions = "1.4.1"
